apiVersion: tekton.dev/v1beta1 
kind: PipelineRun 
metadata:
  name: build-deploy-api-pipelinerun 
spec:
  pipelineRef:
    name: build-and-deploy 
  params: 
  - name: deployment-name
    value: weather-app
  - name: git-url
    value: https://github.com/DavidShermann/CICDOpenShiftTest.git
  - name: IMAGE
    value: doovid1000/weather-app
  workspaces: 
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi